# https://argoproj.github.io/argo-cd/operator-manual/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tbow-emb-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:tbowzz/argo_test.git
    targetRevision: main
    path: argoapp
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

